package uz.ishborApp.Entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "APPLIED".
 */
public class Applied {

    private Long id;
    private String userId;
    private Long vacancyId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Applied() {
    }

    public Applied(Long id) {
        this.id = id;
    }

    public Applied(Long id, String userId, Long vacancyId) {
        this.id = id;
        this.userId = userId;
        this.vacancyId = vacancyId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Long getVacancyId() {
        return vacancyId;
    }

    public void setVacancyId(Long vacancyId) {
        this.vacancyId = vacancyId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
