package uz.ishborApp.Entity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import uz.ishborApp.Entity.Search;
import uz.ishborApp.Entity.Category;
import uz.ishborApp.Entity.Vacancy;

import uz.ishborApp.Entity.SearchDao;
import uz.ishborApp.Entity.CategoryDao;
import uz.ishborApp.Entity.VacancyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig vacancyDaoConfig;

    private final SearchDao searchDao;
    private final CategoryDao categoryDao;
    private final VacancyDao vacancyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchDaoConfig = daoConfigMap.get(SearchDao.class).clone();
        searchDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        vacancyDaoConfig = daoConfigMap.get(VacancyDao.class).clone();
        vacancyDaoConfig.initIdentityScope(type);

        searchDao = new SearchDao(searchDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        vacancyDao = new VacancyDao(vacancyDaoConfig, this);

        registerDao(Search.class, searchDao);
        registerDao(Category.class, categoryDao);
        registerDao(Vacancy.class, vacancyDao);
    }
    
    public void clear() {
        searchDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        vacancyDaoConfig.getIdentityScope().clear();
    }

    public SearchDao getSearchDao() {
        return searchDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public VacancyDao getVacancyDao() {
        return vacancyDao;
    }

}
