package uz.ishborApp.Entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.arlib.floatingsearchview.suggestions.model.SearchSuggestion;

/**
 * Entity mapped to table "SEARCH".
 */
public class Search{

    private Long id;
    private String word;
    private java.util.Date created;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Search() {
    }

    public Search(Long id) {
        this.id = id;
    }

    public Search(Long id, String word, java.util.Date created) {
        this.id = id;
        this.word = word;
        this.created = created;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
